// ValidatorWallet ABI for querying and managing validator wallet
export const VALIDATOR_WALLET_ABI = [
  // Custom errors
  {name: "NotOperator", type: "error", inputs: []},
  {name: "InvalidAddress", type: "error", inputs: []},
  {name: "TransferFailed", type: "error", inputs: []},
  {name: "OperatorTransferNotReady", type: "error", inputs: []},
  {name: "NoPendingOperator", type: "error", inputs: []},

  // Functions
  {
    name: "operator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "owner",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "getIdentity",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "moniker", type: "string"},
          {name: "logoUri", type: "string"},
          {name: "website", type: "string"},
          {name: "description", type: "string"},
          {name: "email", type: "string"},
          {name: "twitter", type: "string"},
          {name: "telegram", type: "string"},
          {name: "github", type: "string"},
          {name: "extraCid", type: "bytes"},
        ],
      },
    ],
  },
  {
    name: "setOperator",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_operator", type: "address"}],
    outputs: [],
  },
  {
    name: "setIdentity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "moniker", type: "string"},
      {name: "logoUri", type: "string"},
      {name: "website", type: "string"},
      {name: "description", type: "string"},
      {name: "email", type: "string"},
      {name: "twitter", type: "string"},
      {name: "telegram", type: "string"},
      {name: "github", type: "string"},
      {name: "extraCid", type: "bytes"},
    ],
    outputs: [],
  },
  // Staking functions (forwarded to staking contract)
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    name: "validatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_shares", type: "uint256"}],
    outputs: [],
  },
  {
    name: "validatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  // Two-step operator transfer
  {
    name: "initiateOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_newOperator", type: "address"}],
    outputs: [],
  },
  {
    name: "completeOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "cancelOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "getPendingOperator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {name: "", type: "address"},
      {name: "", type: "uint256"},
    ],
  },
  {
    name: "getOperator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
] as const;

export const STAKING_ABI = [
  // Custom errors from IGenLayerStaking
  {name: "OnlyGEN", type: "error", inputs: []},
  {name: "OnlyTribunal", type: "error", inputs: []},
  {name: "OnlyIdleness", type: "error", inputs: []},
  {name: "OnlyTransactions", type: "error", inputs: []},
  {name: "OnlyIdlenessOrTribunal", type: "error", inputs: []},
  {name: "OnlyTransactionsOrTribunal", type: "error", inputs: []},
  {name: "InvalidAtEpoch", type: "error", inputs: []},
  {name: "MaxValidatorsCannotBeZero", type: "error", inputs: []},
  {name: "ValidatorExitExceedsShares", type: "error", inputs: []},
  {name: "DelegatorExitExceedsShares", type: "error", inputs: []},
  {name: "DelegatorMayNotJoinWithZeroValue", type: "error", inputs: []},
  {name: "DelegatorMayNotJoinTwoValidatorsSimultaneously", type: "error", inputs: []},
  {name: "DelegatorBelowMinimumStake", type: "error", inputs: []},
  {name: "DelegatorExitWouldBeBelowMinimum", type: "error", inputs: []},
  {name: "ValidatorNotActive", type: "error", inputs: []},
  {name: "ValidatorMayNotBeDelegator", type: "error", inputs: []},
  {name: "ValidatorMustNotBeDelegator", type: "error", inputs: []},
  {name: "ValidatorMayNotJoinWithZeroValue", type: "error", inputs: []},
  {name: "ValidatorMayNotDepositZeroValue", type: "error", inputs: []},
  {name: "ValidatorWithdrawalExceedsStake", type: "error", inputs: []},
  {name: "ValidatorAlreadyJoined", type: "error", inputs: []},
  {name: "ValidatorNotJoined", type: "error", inputs: []},
  {name: "ValidatorBelowMinimumStake", type: "error", inputs: []},
  {name: "OperatorAlreadyAssigned", type: "error", inputs: []},
  {name: "InvalidOperatorAddress", type: "error", inputs: []},
  {name: "MaxNumberOfValidatorsReached", type: "error", inputs: []},
  {name: "ValidatorsConsumed", type: "error", inputs: []},
  {name: "ValidatorsUnavailable", type: "error", inputs: []},
  {name: "EpochNotFinished", type: "error", inputs: []},
  {name: "EpochNotFinalized", type: "error", inputs: []},
  {name: "InflationInvalidAmount", type: "error", inputs: []},
  {name: "InflationAlreadyReceived", type: "error", inputs: []},
  {name: "InflationAlreadyInitialized", type: "error", inputs: []},
  {name: "EpochAlreadyFinalized", type: "error", inputs: []},
  {name: "PendingTribunals", type: "error", inputs: [{name: "epoch", type: "uint256"}]},
  {name: "FailedTransfer", type: "error", inputs: [{name: "validator", type: "address"}]},
  {name: "NFTMinterCallFailed", type: "error", inputs: []},
  {name: "DeepthoughtCallFailed", type: "error", inputs: []},
  {name: "NFTMinterNotConfigured", type: "error", inputs: []},
  {name: "NumberOfValidatorsExceedsAvailable", type: "error", inputs: []},
  {name: "EpochAdvanceNotReady", type: "error", inputs: []},
  {name: "PreviousEpochNotFinalizable", type: "error", inputs: []},
  {name: "NoBurning", type: "error", inputs: []},
  {name: "ReductionFactorCannotBeZero", type: "error", inputs: []},

  // Validator functions
  {
    name: "validatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [{name: "validator", type: "address"}],
  },
  {
    name: "validatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "_operator", type: "address"}],
    outputs: [{name: "validator", type: "address"}],
  },
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    name: "validatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_sharesWithdrawal", type: "uint256"}],
    outputs: [],
  },
  {
    name: "validatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorPrime",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  // Delegator functions
  {
    name: "delegatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  {
    name: "delegatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_sharesExit", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "delegatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [],
  },
  // View functions
  {
    name: "isValidator",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_address", type: "address"}],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "validatorView",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "left", type: "address"},
          {name: "right", type: "address"},
          {name: "parent", type: "address"},
          {name: "eBanned", type: "uint256"},
          {name: "ePrimed", type: "uint256"},
          {name: "vStake", type: "uint256"},
          {name: "vShares", type: "uint256"},
          {name: "dStake", type: "uint256"},
          {name: "dShares", type: "uint256"},
          {name: "vDeposit", type: "uint256"},
          {name: "vWithdrawal", type: "uint256"},
          {name: "live", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "sharesOf",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "stakeOf",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epoch",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "finalized",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorMinStake",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "delegatorMinStake",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "activeValidators",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "activeValidatorsCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epochOdd",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "start", type: "uint256"},
          {name: "end", type: "uint256"},
          {name: "inflation", type: "uint256"},
          {name: "weight", type: "uint256"},
          {name: "weightDeposit", type: "uint256"},
          {name: "weightWithdrawal", type: "uint256"},
          {name: "vcount", type: "uint256"},
          {name: "claimed", type: "uint256"},
          {name: "stakeDeposit", type: "uint256"},
          {name: "stakeWithdrawal", type: "uint256"},
          {name: "slashed", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "epochEven",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "start", type: "uint256"},
          {name: "end", type: "uint256"},
          {name: "inflation", type: "uint256"},
          {name: "weight", type: "uint256"},
          {name: "weightDeposit", type: "uint256"},
          {name: "weightWithdrawal", type: "uint256"},
          {name: "vcount", type: "uint256"},
          {name: "claimed", type: "uint256"},
          {name: "stakeDeposit", type: "uint256"},
          {name: "stakeWithdrawal", type: "uint256"},
          {name: "slashed", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "epochMinDuration",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epochZeroMinDuration",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "getQuarantinedValidators",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "getAllQuarantinedValidators",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "getAllBannedValidators",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  // Deposit query functions
  {
    name: "validatorDepositLen",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "len_", type: "uint256"}],
  },
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {name: "epoch_", type: "uint256"},
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorDepositLen",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "delegatorDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {
        name: "claim_",
        type: "tuple",
        components: [
          {name: "quantity", type: "uint256"},
          {name: "commit", type: "uint256"},
        ],
      },
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  // Withdrawal query functions
  {
    name: "validatorWithdrawalLen",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "len_", type: "uint256"}],
  },
  {
    name: "validatorWithdrawal",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {name: "epoch_", type: "uint256"},
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorWithdrawalLen",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "delegatorWithdrawal",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {
        name: "claim_",
        type: "tuple",
        components: [
          {name: "quantity", type: "uint256"},
          {name: "commit", type: "uint256"},
        ],
      },
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  // Events (none indexed to match deployed contract)
  {
    name: "ValidatorJoin",
    type: "event",
    inputs: [
      {name: "operator", type: "address", indexed: false},
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorDeposit",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorExit",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "shares", type: "uint256", indexed: false},
    ],
  },
  {
    name: "DelegatorJoin",
    type: "event",
    inputs: [
      {name: "delegator", type: "address", indexed: false},
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorPrime",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
      {name: "validatorRewards", type: "uint256", indexed: false},
      {name: "delegatorRewards", type: "uint256", indexed: false},
    ],
  },
  // External contracts getter
  {
    name: "contracts",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {name: "gen", type: "address"},
      {name: "transactions", type: "address"},
      {name: "idleness", type: "address"},
      {name: "tribunal", type: "address"},
      {name: "slashing", type: "address"},
      {name: "consensus", type: "address"},
      {name: "validatorWalletFactory", type: "address"},
      {name: "nftMinter", type: "address"},
    ],
  },
] as const;

// Slash contract ABI for slashing events
export const SLASH_ABI = [
  {
    name: "SlashedFromIdleness",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: true},
      {name: "txId", type: "bytes32", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
      {name: "percentage", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SlashEnacted",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: true},
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
] as const;
