export const CONSENSUS_ADDRESS_MANAGER_ABI = [
  {
    name: "getAddressManager",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
] as const;

export const ADDRESS_MANAGER_ABI = [
  {name: "ZeroAddress", type: "error", inputs: [{name: "key", type: "string"}]},
  {name: "ArrayLengthMismatch", type: "error", inputs: []},
  {
    name: "AddressUpdated",
    type: "event",
    inputs: [
      {name: "key", type: "string", indexed: true},
      {name: "oldAddr", type: "address", indexed: true},
      {name: "newAddr", type: "address", indexed: true},
    ],
  },
  {name: "getAddress", type: "function", stateMutability: "view", inputs: [{name: "key", type: "string"}], outputs: [{name: "", type: "address"}]},
  {name: "getAddressNonZero", type: "function", stateMutability: "view", inputs: [{name: "key", type: "string"}], outputs: [{name: "", type: "address"}]},
  {name: "addressBook", type: "function", stateMutability: "view", inputs: [{name: "key", type: "string"}], outputs: [{name: "", type: "address"}]},
  {
    name: "getAllContractAddresses",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "tuple[]", components: [{name: "key", type: "string"}, {name: "addr", type: "address"}]}],
  },
  {name: "getContractKeyCount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
] as const;

export const VESTING_ABI = [
  {name: "NotBeneficiary", type: "error", inputs: []},
  {name: "NotRevoker", type: "error", inputs: []},
  {name: "NotCreator", type: "error", inputs: []},
  {name: "NotRevocable", type: "error", inputs: []},
  {name: "AlreadyRevoked", type: "error", inputs: []},
  {name: "NotRevoked", type: "error", inputs: []},
  {name: "AlreadyUnlocked", type: "error", inputs: []},
  {name: "ManualUnlockNotRequired", type: "error", inputs: []},
  {name: "WithdrawExceedsVested", type: "error", inputs: []},
  {name: "InsufficientContractBalance", type: "error", inputs: []},
  {name: "ZeroAmount", type: "error", inputs: []},
  {name: "TransferFailed", type: "error", inputs: []},
  {name: "VestingAlreadyStopped", type: "error", inputs: []},
  {name: "VestingNotStopped", type: "error", inputs: []},
  {name: "InvalidStopTimestamp", type: "error", inputs: []},
  {name: "NoValidatorWallet", type: "error", inputs: []},
  {name: "InvalidAddress", type: "error", inputs: []},
  {name: "VestingAlreadyExists", type: "error", inputs: []},
  {name: "VestingDeploymentFailed", type: "error", inputs: []},
  {name: "BeaconNotDeployed", type: "error", inputs: []},
  {name: "BeaconAlreadyDeployed", type: "error", inputs: []},
  {name: "FundingMismatch", type: "error", inputs: []},
  {name: "InvalidCliffUnlockBps", type: "error", inputs: []},
  {name: "InvalidPeriodDuration", type: "error", inputs: []},
  {
    name: "VestingInitialized",
    type: "event",
    inputs: [
      {name: "name", type: "string", indexed: false},
      {name: "beneficiary", type: "address", indexed: true},
      {name: "totalAmount", type: "uint256", indexed: false},
      {name: "startDate", type: "uint256", indexed: false},
      {name: "category", type: "uint8", indexed: false},
    ],
  },
  {name: "TokensWithdrawn", type: "event", inputs: [{name: "beneficiary", type: "address", indexed: true}, {name: "amount", type: "uint256", indexed: false}]},
  {name: "DelegatorJoined", type: "event", inputs: [{name: "validator", type: "address", indexed: true}, {name: "amount", type: "uint256", indexed: false}]},
  {name: "DelegatorExited", type: "event", inputs: [{name: "validator", type: "address", indexed: true}, {name: "shares", type: "uint256", indexed: false}]},
  {name: "DelegatorClaimed", type: "event", inputs: [{name: "validator", type: "address", indexed: true}, {name: "returned", type: "uint256", indexed: false}, {name: "rewardOrLoss", type: "int256", indexed: false}]},
  {name: "ValidatorJoined", type: "event", inputs: [{name: "wallet", type: "address", indexed: true}, {name: "operator", type: "address", indexed: true}, {name: "amount", type: "uint256", indexed: false}]},
  {name: "ValidatorDeposited", type: "event", inputs: [{name: "wallet", type: "address", indexed: true}, {name: "amount", type: "uint256", indexed: false}]},
  {name: "ValidatorExited", type: "event", inputs: [{name: "wallet", type: "address", indexed: true}, {name: "shares", type: "uint256", indexed: false}]},
  {name: "ValidatorClaimed", type: "event", inputs: [{name: "wallet", type: "address", indexed: true}, {name: "returned", type: "uint256", indexed: false}, {name: "rewardOrLoss", type: "int256", indexed: false}]},
  {name: "Revoked", type: "event", inputs: [{name: "vestedAtRevocation", type: "uint256", indexed: false}, {name: "totalAmountAtRevocation", type: "uint256", indexed: false}]},
  {name: "VestingStopped", type: "event", inputs: [{name: "stopTimestamp", type: "uint256", indexed: false}]},
  {name: "VestingResumed", type: "event", inputs: []},
  {name: "ManuallyUnlocked", type: "event", inputs: []},
  {name: "TopUp", type: "event", inputs: [{name: "amount", type: "uint256", indexed: false}, {name: "reason", type: "string", indexed: false}]},
  {name: "FoundationSwept", type: "event", inputs: [{name: "amount", type: "uint256", indexed: false}]},
  {name: "NameSet", type: "event", inputs: [{name: "oldName", type: "string", indexed: false}, {name: "newName", type: "string", indexed: false}]},
  {name: "CategorySet", type: "event", inputs: [{name: "oldCategory", type: "uint8", indexed: false}, {name: "newCategory", type: "uint8", indexed: false}]},
  {name: "StartDateSet", type: "event", inputs: [{name: "oldStartDate", type: "uint256", indexed: false}, {name: "newStartDate", type: "uint256", indexed: false}]},
  {name: "CliffDurationSet", type: "event", inputs: [{name: "oldCliffDuration", type: "uint256", indexed: false}, {name: "newCliffDuration", type: "uint256", indexed: false}]},
  {name: "PeriodDurationSet", type: "event", inputs: [{name: "oldPeriodDuration", type: "uint256", indexed: false}, {name: "newPeriodDuration", type: "uint256", indexed: false}]},
  {name: "NumberOfPeriodsSet", type: "event", inputs: [{name: "oldNumberOfPeriods", type: "uint256", indexed: false}, {name: "newNumberOfPeriods", type: "uint256", indexed: false}]},
  {name: "CliffUnlockBpsSet", type: "event", inputs: [{name: "oldCliffUnlockBps", type: "uint256", indexed: false}, {name: "newCliffUnlockBps", type: "uint256", indexed: false}]},
  {name: "BeneficiarySet", type: "event", inputs: [{name: "oldBeneficiary", type: "address", indexed: true}, {name: "newBeneficiary", type: "address", indexed: true}]},
  {name: "CreatorSet", type: "event", inputs: [{name: "oldCreator", type: "address", indexed: true}, {name: "newCreator", type: "address", indexed: true}]},

  {name: "name", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "string"}]},
  {name: "category", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint8"}]},
  {name: "beneficiary", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "creator", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "revoker", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "factory", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "addressManager", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "totalAmount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "startDate", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "cliffDuration", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "periodDuration", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "numberOfPeriods", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "cliffUnlockBps", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "needsManualUnlock", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "bool"}]},
  {name: "manualUnlocked", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "bool"}]},
  {name: "revoked", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "bool"}]},
  {name: "vestingStopped", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "bool"}]},
  {name: "totalWithdrawn", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "vestedAtRevocation", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "totalAmountAtRevocation", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "revokedAt", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "vestingStoppedAt", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "vestedAtStop", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "postRevocationBeneficiaryRewards", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "postRevocationBeneficiaryLosses", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "depositedPerValidator", type: "function", stateMutability: "view", inputs: [{name: "validator", type: "address"}], outputs: [{name: "", type: "uint256"}]},
  {name: "pendingExitDeposited", type: "function", stateMutability: "view", inputs: [{name: "validator", type: "address"}], outputs: [{name: "", type: "uint256"}]},
  {name: "accumulatedRewards", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "accumulatedLosses", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "validatorWallets", type: "function", stateMutability: "view", inputs: [{name: "index", type: "uint256"}], outputs: [{name: "", type: "address"}]},
  {name: "isValidatorWallet", type: "function", stateMutability: "view", inputs: [{name: "wallet", type: "address"}], outputs: [{name: "", type: "bool"}]},
  {name: "validatorDeposited", type: "function", stateMutability: "view", inputs: [{name: "wallet", type: "address"}], outputs: [{name: "", type: "uint256"}]},
  {name: "getValidatorWallets", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address[]"}]},
  {name: "validatorWalletCount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "vestedAmount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "unvestedAmount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "withdrawableAmount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},

  {name: "vestingWithdraw", type: "function", stateMutability: "nonpayable", inputs: [{name: "amount", type: "uint256"}], outputs: []},
  {name: "vestingDelegatorJoin", type: "function", stateMutability: "nonpayable", inputs: [{name: "validator", type: "address"}, {name: "amount", type: "uint256"}], outputs: []},
  {name: "vestingDelegatorExit", type: "function", stateMutability: "nonpayable", inputs: [{name: "validator", type: "address"}, {name: "shares", type: "uint256"}], outputs: []},
  {name: "vestingDelegatorClaim", type: "function", stateMutability: "nonpayable", inputs: [{name: "validator", type: "address"}], outputs: []},
  {
    name: "vestingValidatorJoin",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "operatorPubKey", type: "uint256[2]"},
      {name: "possessionProof", type: "bytes"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [],
  },
  {name: "vestingValidatorDeposit", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}, {name: "amount", type: "uint256"}], outputs: []},
  {name: "vestingValidatorExit", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}, {name: "shares", type: "uint256"}], outputs: []},
  {name: "vestingValidatorClaim", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}], outputs: []},
  {name: "vestingValidatorInitiateOperatorTransfer", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}, {name: "newOperator", type: "address"}], outputs: []},
  {name: "vestingValidatorCompleteOperatorTransfer", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}], outputs: []},
  {name: "vestingValidatorCancelOperatorTransfer", type: "function", stateMutability: "nonpayable", inputs: [{name: "wallet", type: "address"}], outputs: []},
  {
    name: "vestingValidatorSetIdentity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "wallet", type: "address"},
      {name: "moniker", type: "string"},
      {name: "logoUri", type: "string"},
      {name: "website", type: "string"},
      {name: "description", type: "string"},
      {name: "email", type: "string"},
      {name: "twitter", type: "string"},
      {name: "telegram", type: "string"},
      {name: "github", type: "string"},
      {name: "extraCid", type: "bytes"},
    ],
    outputs: [],
  },
  {name: "revoke", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "stopVesting", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "resumeVesting", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "foundationSweep", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "manualUnlock", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "topUp", type: "function", stateMutability: "payable", inputs: [{name: "reason", type: "string"}], outputs: []},
  {name: "setName", type: "function", stateMutability: "nonpayable", inputs: [{name: "_name", type: "string"}], outputs: []},
  {name: "setCategory", type: "function", stateMutability: "nonpayable", inputs: [{name: "_category", type: "uint8"}], outputs: []},
  {name: "setStartDate", type: "function", stateMutability: "nonpayable", inputs: [{name: "_startDate", type: "uint256"}], outputs: []},
  {name: "setCliffDuration", type: "function", stateMutability: "nonpayable", inputs: [{name: "_cliffDuration", type: "uint256"}], outputs: []},
  {name: "setPeriodDuration", type: "function", stateMutability: "nonpayable", inputs: [{name: "_periodDuration", type: "uint256"}], outputs: []},
  {name: "setNumberOfPeriods", type: "function", stateMutability: "nonpayable", inputs: [{name: "_numberOfPeriods", type: "uint256"}], outputs: []},
  {name: "setCliffUnlockBps", type: "function", stateMutability: "nonpayable", inputs: [{name: "_cliffUnlockBps", type: "uint256"}], outputs: []},
  {name: "setBeneficiary", type: "function", stateMutability: "nonpayable", inputs: [{name: "_beneficiary", type: "address"}], outputs: []},
  {name: "setCreator", type: "function", stateMutability: "nonpayable", inputs: [{name: "_creator", type: "address"}], outputs: []},
] as const;

export const VESTING_FACTORY_ABI = [
  {name: "InvalidAddress", type: "error", inputs: []},
  {name: "VestingAlreadyExists", type: "error", inputs: []},
  {name: "VestingDeploymentFailed", type: "error", inputs: []},
  {name: "BeaconNotDeployed", type: "error", inputs: []},
  {name: "BeaconAlreadyDeployed", type: "error", inputs: []},
  {name: "FundingMismatch", type: "error", inputs: []},
  {name: "InvalidCliffUnlockBps", type: "error", inputs: []},
  {name: "InvalidPeriodDuration", type: "error", inputs: []},
  {name: "ZeroAmount", type: "error", inputs: []},
  {name: "OwnableUnauthorizedAccount", type: "error", inputs: [{name: "account", type: "address"}]},
  {name: "OwnableInvalidOwner", type: "error", inputs: [{name: "owner", type: "address"}]},
  {name: "VestingCreated", type: "event", inputs: [{name: "beneficiary", type: "address", indexed: true}, {name: "vestingContract", type: "address", indexed: true}, {name: "totalAmount", type: "uint256", indexed: false}, {name: "category", type: "uint8", indexed: false}]},
  {name: "BeaconDeployed", type: "event", inputs: [{name: "beacon", type: "address", indexed: true}, {name: "implementation", type: "address", indexed: true}]},
  {name: "BeaconUpgraded", type: "event", inputs: [{name: "newImplementation", type: "address", indexed: true}]},
  {name: "VestingBlueprintSet", type: "event", inputs: [{name: "blueprint", type: "address", indexed: true}]},
  {name: "INITIALIZE_SELECTOR", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "bytes4"}]},
  {name: "addressManager", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "vestingBlueprint", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "vestingBeacon", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address"}]},
  {name: "beneficiaryToVesting", type: "function", stateMutability: "view", inputs: [{name: "", type: "address"}], outputs: [{name: "", type: "address"}]},
  {name: "isVestingContract", type: "function", stateMutability: "view", inputs: [{name: "", type: "address"}], outputs: [{name: "", type: "bool"}]},
  {name: "totalVestingsDeployed", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {
    name: "createVesting",
    type: "function",
    stateMutability: "payable",
    inputs: [
      {name: "_name", type: "string"}, {name: "_beneficiary", type: "address"}, {name: "_revoker", type: "address"},
      {name: "_startDate", type: "uint256"}, {name: "_cliffDuration", type: "uint256"}, {name: "_periodDuration", type: "uint256"},
      {name: "_numberOfPeriods", type: "uint256"}, {name: "_cliffUnlockBps", type: "uint256"}, {name: "_needsManualUnlock", type: "bool"},
      {name: "_totalAmount", type: "uint256"}, {name: "_category", type: "uint8"},
    ],
    outputs: [{name: "vestingContract", type: "address"}],
  },
  {
    name: "createBatchVesting",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "params", type: "tuple[]", components: [
      {name: "name", type: "string"}, {name: "beneficiary", type: "address"}, {name: "revoker", type: "address"},
      {name: "startDate", type: "uint256"}, {name: "cliffDuration", type: "uint256"}, {name: "periodDuration", type: "uint256"},
      {name: "numberOfPeriods", type: "uint256"}, {name: "cliffUnlockBps", type: "uint256"}, {name: "needsManualUnlock", type: "bool"},
      {name: "totalAmount", type: "uint256"}, {name: "category", type: "uint8"},
    ]}],
    outputs: [{name: "vestingContracts", type: "address[]"}],
  },
  {name: "deployNewBeacon", type: "function", stateMutability: "nonpayable", inputs: [], outputs: []},
  {name: "upgradeBeacon", type: "function", stateMutability: "nonpayable", inputs: [{name: "newImplementation", type: "address"}], outputs: []},
  {name: "setVestingBlueprint", type: "function", stateMutability: "nonpayable", inputs: [{name: "_blueprint", type: "address"}], outputs: []},
  {name: "setAddressManager", type: "function", stateMutability: "nonpayable", inputs: [{name: "_addressManager", type: "address"}], outputs: []},
  {name: "getVesting", type: "function", stateMutability: "view", inputs: [{name: "_beneficiary", type: "address"}], outputs: [{name: "", type: "address"}]},
  {name: "getMyVestings", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address[]"}]},
  {name: "getMyVestingCount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "getAllVestings", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "address[]"}]},
  {name: "getAllVestingsCount", type: "function", stateMutability: "view", inputs: [], outputs: [{name: "", type: "uint256"}]},
  {name: "isVestingAddress", type: "function", stateMutability: "view", inputs: [{name: "_wallet", type: "address"}], outputs: [{name: "", type: "bool"}]},
] as const;
